name: mips64 qemu test

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  TEST:
    if: "github.repository == 'OpenMathLib/OpenBLAS'"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: MIPS64_GENERIC
            triple: mips64el-linux-gnuabi64
            opts: NO_SHARED=1 TARGET=MIPS64_GENERIC
          - target: SICORTEX
            triple: mips64el-linux-gnuabi64
            opts: NO_SHARED=1 TARGET=SICORTEX
          - target: I6400
            triple: mipsisa64r6el-linux-gnuabi64
            opts: NO_SHARED=1 TARGET=I6400
          - target: P6600
            triple: mipsisa64r6el-linux-gnuabi64
            opts: NO_SHARED=1 TARGET=P6600
          - target: I6500
            triple: mipsisa64r6el-linux-gnuabi64
            opts: NO_SHARED=1 TARGET=I6500

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install build deps
        run: |
          sudo apt-get update
          sudo apt-get install autoconf automake autotools-dev ninja-build make ccache \
          gcc-${{ matrix.triple }} gfortran-${{ matrix.triple }} libgomp1-mips64el-cross

      - name: checkout qemu
        uses: actions/checkout@v3
        with:
          repository: qemu/qemu
          path: qemu
          ref: 79dfa177ae348bb5ab5f97c0915359b13d6186e2

      - name: build qemu
        run: |
          cd qemu
          ./configure --prefix=$GITHUB_WORKSPACE/qemu-install --target-list=mips64el-linux-user --disable-system
          make -j$(nproc)
          make install

      - name: Compilation cache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ccache-${{ runner.os }}-${{ matrix.target }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ccache-${{ runner.os }}-${{ matrix.target }}-${{ github.ref }}
            ccache-${{ runner.os }}-${{ matrix.target }}

      - name: Configure ccache
        run: |
          test -d ~/.ccache || mkdir -p ~/.ccache
          echo "max_size = 300M" > ~/.ccache/ccache.conf
          echo "compression = true" >> ~/.ccache/ccache.conf
          ccache -s

      - name: build OpenBLAS
        run: make CC='ccache ${{ matrix.triple }}-gcc -static' FC='ccache ${{ matrix.triple }}-gfortran -static' ${{ matrix.opts }} HOSTCC='ccache gcc' -j$(nproc)

      - name: test
        run: |
          export PATH=$GITHUB_WORKSPACE/qemu-install/bin/:$PATH
          qemu-mips64el ./utest/openblas_utest
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./ctest/xscblat1
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./ctest/xdcblat1
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./ctest/xccblat1
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./ctest/xzcblat1
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./ctest/xscblat2 < ./ctest/sin2
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./ctest/xdcblat2 < ./ctest/din2
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./ctest/xccblat2 < ./ctest/cin2
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./ctest/xzcblat2 < ./ctest/zin2
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./ctest/xscblat3 < ./ctest/sin3
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./ctest/xdcblat3 < ./ctest/din3
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./ctest/xccblat3 < ./ctest/cin3
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./ctest/xzcblat3 < ./ctest/zin3
          OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 qemu-mips64el ./test/sblat1
          OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 qemu-mips64el ./test/dblat1
          OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 qemu-mips64el ./test/cblat1
          OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 qemu-mips64el ./test/zblat1
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./test/sblat1
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./test/dblat1
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./test/cblat1
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./test/zblat1
          rm -f ./test/?BLAT2.SUMM
          OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 qemu-mips64el ./test/sblat2 < ./test/sblat2.dat
          OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 qemu-mips64el ./test/dblat2 < ./test/dblat2.dat
          OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 qemu-mips64el ./test/cblat2 < ./test/cblat2.dat
          OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 qemu-mips64el ./test/zblat2 < ./test/zblat2.dat
          rm -f ./test/?BLAT2.SUMM
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./test/sblat2 < ./test/sblat2.dat
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./test/dblat2 < ./test/dblat2.dat
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./test/cblat2 < ./test/cblat2.dat
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./test/zblat2 < ./test/zblat2.dat
          rm -f ./test/?BLAT3.SUMM
          OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 qemu-mips64el ./test/sblat3 < ./test/sblat3.dat
          OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 qemu-mips64el ./test/dblat3 < ./test/dblat3.dat
          OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 qemu-mips64el ./test/cblat3 < ./test/cblat3.dat
          OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 qemu-mips64el ./test/zblat3 < ./test/zblat3.dat
          rm -f ./test/?BLAT3.SUMM
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./test/sblat3 < ./test/sblat3.dat
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./test/dblat3 < ./test/dblat3.dat
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./test/cblat3 < ./test/cblat3.dat
          OPENBLAS_NUM_THREADS=2 qemu-mips64el ./test/zblat3 < ./test/zblat3.dat
